name: UAGRM Bot Scraper

on:
  schedule:
    - cron: '*/30 * * * *' # Se ejecuta automáticamente cada 30 minutos
  workflow_dispatch: # Nos pone un botón en la página de GitHub para ejecutarlo a mano cuando queramos

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest # Usamos el hermano mayor de tu Lubuntu

    steps:
    - name: 1. Descargar el código de tu repositorio
      uses: actions/checkout@v3

    - name: 2. Configurar Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: 3. Instalar librerías y la Pantalla Fantasma (Xvfb)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y xvfb
        # Quitamos la instalación de Chromium porque usaremos el Chrome de fábrica

    - name: 4. Ejecutar el bot dentro de la pantalla fantasma
      env:
        UAGRM_USER: ${{ secrets.UAGRM_USER }}
        UAGRM_PASS: ${{ secrets.UAGRM_PASS }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      run: |
        # Agregamos "-u" para que Python imprima los mensajes en vivo
        xvfb-run --auto-servernum python -u main.py